src/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for, make_response, current_app
from src.models import SignIn, User
from src import db
from src.users.forms import SignInForm, ContactForm
from src.services import business_url_return, EmailService, create_cookie, grab_cookie
from src.users.decorators import verify_business

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/contact", methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        if current_app.config["FLASK_ENV"] == 'production':
            body_html = render_template(
                'mail/user/contact_email.html',
                name=form.name.data,
                message=form.message.data,
                email=form.email.data
            )
            body_text = render_template(
                'mail/user/contact_email.txt',
                name=form.name.data,
                message=form.message.data,
                email=form.email.data
            )
            EmailService.email('admin@c-sign.in', 'New message.', body_html, body_text)
        return render_template('success.html', type='email')
    return render_template('contact.html', title='Contact Us', form=form)


@main.route("/signin/<string:business_name>", methods=['GET', 'POST'])
@verify_business
def sign_in(business_name):
    """
    Main sign in function.
    Will search the database for existing business taken from the url, if not found will return 404.
    If user has previously signed in within the last 4 hours they will not need to sign in again as a
    cookie will store their previous login.
    :param business_name:
    :return:
    """
    req = request
    business = User.query.filter_by(business_url=business_name).first_or_404()
    logo = url_for('static', filename='profile_pics/' + business.logo)
    form = SignInForm()
    if form.validate_on_submit():
        new_sign_in = SignIn(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            phone=form.phone_number.data,
            symptoms=form.symptoms.data,
            signup=form.sign_up.data,
            user_id=business
        )
        db.session.add(new_sign_in)
        db.session.commit()
        if business.menu_url is not None:
            bu = business_url_return(business.menu_url)
            res = make_response(redirect(bu))
            # Set sign in to 4 hours so guest can re-scan the code
            res.set_cookie(business_name, 'signed_in', secure=True, max_age=60 * 60 * 4)
            if not request.cookies.get('csign'):
                create_cookie(res, form)
            return res
        else:
            flash('You have been signed in!', 'success')
            return render_template('signin.html', logo=logo, business_name=business_name, form=form)

    elif request.method == 'GET':
        bu = business_url_return(business.menu_url)
        res = make_response(redirect(bu))
        return res
        if request.cookies.get('csign'):
            # pull cookie information
            grab_cookie(form, request)
        if request.cookies.get(business_name):
            if business.menu_url is not None:
                bu = business_url_return(business.menu_url)
                res = make_response(redirect(bu))
                return res
        return render_template('signin.html', logo=logo, business_name=business.business_name, form=form)
    return render_template('signin.html', logo=logo, business_name=business.business_name, form=form)

src/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, send_from_directory, abort, current_app
from src import db, bcrypt
from src.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                             RequestResetForm, ResetPasswordForm)
from src.services import save_picture, save_csv, EmailService, generate_qr, strip_chars, Encryption
from src.models import User
from src.users.decorators import admin_required
from flask_login import login_user, current_user, logout_user, login_required
import os

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email=form.email.data,
                    business_name=form.business_name.data,
                    business_url=strip_chars(form.business_name.data),
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    phone_number=form.phone_number.data,
                    address=form.address.data,
                    post_code=form.post_code.data,
                    state=form.state.data,
                    menu_url=form.menu_url.data,
                    qr_image=generate_qr(form.business_name.data),
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        if current_app.config['FLASK_ENV'] == 'production':
            EmailService.send_confirm_email(user)
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.account'))
        else:
            flash('Login not found. Please check email and password', 'danger')
    return render_template('login.html', title='login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.logo.data:
            picture_file = save_picture(form.logo.data)
            current_user.logo = picture_file
        current_user.menu_url = form.menu_url.data
        if form.business_url.data != current_user.business_url:
            current_user.business_url = strip_chars(form.business_url.data).lower()
            generate_qr(form.business_url.data)
        current_user.email = form.email.data
        current_user.business_name = form.business_name.data
        if form.api_key.data:
            current_user.mail_api = Encryption.encrypt_user_data(form.api_key.data.encode())
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.business_name.data = current_user.business_name
        form.menu_url.data = current_user.menu_url
        form.business_url.data = current_user.business_url
        form.email.data = current_user.email
        if current_user.mail_api:
            form.api_key.data = Encryption.decrypt_user_data(current_user.mail_api).decode()
        else:
            form.api_key.data = current_user.mail_api
    logo = url_for('static', filename='profile_pics/' + current_user.logo)
    # Serve files from cloudfront if server is in production
    if current_app.config["FLASK_ENV"] == 'production':
        qr_file = f'https://ddjesgdltvd54.cloudfront.net/qr_codes/{current_user.qr_image}'
    else:
        qr_file = url_for('static', filename='qr_codes/' + current_user.qr_image)
    return render_template('account.html', title='Account', logo=logo, qr_file=qr_file, form=form)


@users.route("/account/change_password", methods=['GET', 'POST'])
@login_required
def change_password():
    form = ResetPasswordForm()
    if form.validate_on_submit():
        current_user.password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        db.session.commit()
        return redirect(url_for('users.account'))
    return render_template('change_password.html', form=form)


@users.route("/download-csv")
@login_required
def download_csv():
    try:
        filename = save_csv(current_user.id)
        return send_from_directory(os.path.join(os.getcwd(),'src/static/csv'), filename=filename, as_attachment=True)
    except FileNotFoundError:
        abort(404)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        EmailService.send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if user is None:
        flash('That token is invalid or expired', 'warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has now been updated!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/verify_user/<token>", methods=['GET'])
def verify_user(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if user is None:
        flash('That token is invalid or expired', 'warning')
        return redirect(url_for('users.login'))
    user.verified = True
    db.session.commit()
    flash('You are now verified!', 'success')
    return redirect(url_for('users.account'))


@users.route("/admin", methods=["GET", "POST"])
@admin_required
def admin():
    list_users = User.query.get().all()
    return render_template('admin.html', title='Admin', users=list_users)

src/templates/about.html
{% extends "layout.html" %}
{% block content %}
        <h1>About Page</h1>
{% endblock content %}

src/templates/admin.html
{% extends "layout.html" %}
{% block content %}
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Users</th>
                <th>Approve</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            {% if user.verified %}
            <tr>
                <td>{{ user.business_name }} | {{ user.email }}</td>
                <td><a href="">Approve</a></td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

src/templates/change_password.html
{% extends "layout.html" %}
{% block content %}
<div class="login-clean">
        <form method="POST" action="" enctype="multipart/form-data">
            <div>
                <h4>{{ current_user.business_name }}</h4>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Change Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary btn-block") }}
            </div>
        </form>
</div>
{% endblock content %}

src/templates/footer.html
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Location</h4>
                <p>1234, 123-4456<br>George Street<br>Sydney, 2000</p>
            </div>
            <div class="col-md-4 mb-5 mb-lg-0" style="color: rgba(255,255,255,0);"></div>
            <div class="col-md-4">
                <h4 class="text-uppercase mb-4">Wanna talk?</h4>
                <p class="lead mb-0"><span><a href="{{ url_for('main.contact') }}">Contact us</a></span></p>
            </div>
        </div>
    </div>
</footer>

src/templates/home.html
{% extends "layout.html" %}
{% block content %}
<header class="masthead bg-primary text-white text-center">
    <div class="container">
        <h1>C-Sign In</h1>
        <hr class="star-light">
        <h2 class="font-weight-light mb-0">Modular, stress free covid sign in</h2>
    </div>
</header>
<section class="portfolio">
    <div class="container">
        <h2 class="text-uppercase text-center text-secondary">Much modules such efficient!</h2>
        <div class="row" style="padding: 40px;">
            <div class="col-md-6 col-lg-4">
                <a class="d-block mx-auto portfolio-item" data-toggle="modal" href="#portfolio-modal-1">
                    <div class="d-flex portfolio-item-caption position-absolute h-100 w-100">
                        <div class="my-auto portfolio-item-caption-content w-100 text-center text-white"><span>Keep your data.</span></div>
                    </div><img class="img-fluid" src="static/img/portfolio/cabin.png"></a>
            </div>
            <div class="col-md-6 col-lg-4">
                <a class="d-block mx-auto portfolio-item" data-toggle="modal" href="#portfolio-modal-2">
                    <div class="d-flex portfolio-item-caption position-absolute h-100 w-100">
                        <div class="my-auto portfolio-item-caption-content w-100 text-center text-white"><span>Serve your menu.</span></div>
                    </div><img class="img-fluid" src="static/img/portfolio/cake.png"></a>
            </div>
            <div class="col-md-6 col-lg-4">
                <a class="d-block mx-auto portfolio-item" data-toggle="modal" href="#portfolio-modal-3">
                    <div class="d-flex portfolio-item-caption position-absolute h-100 w-100">
                        <div class="my-auto portfolio-item-caption-content w-100 text-center text-white">Privacy law compliant.</div>
                    </div><img class="img-fluid" src="static/img/portfolio/circus.png"></a>
            </div>
        </div>
    </div>
</section>
<section id="about" class="bg-primary text-white mb-0">
    <div class="container">
        <h2 class="text-uppercase text-center text-white">Why C-sign?</h2>
        <hr class="star-light mb-5">
        <div class="row">
            <div class="col-lg-4 ml-auto">
                <p class="lead">Want to be able to redirect the people you sign in to your menu, ordering or info page straight away without having them scan another 10 QR codes? Well, we got ya!</p>
            </div>
            <div class="col-lg-4 mr-auto">
                <p class="lead">C-Sign makes it easy to get the information into your customers hands. We provide you with a QR code as soon as you sign up and you have access to your data whenever you want it.</p>
            </div>
        </div>
        <div class="text-center mt-4"><a class="btn btn-outline-light btn-xl" role="button" href="{{ url_for('users.register') }}"><i class="fa fa-check mr-2"></i><span>Sign Up Now!</span></a></div>
    </div>
</section>
{% endblock content %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>C-Sign - {{ title }}</title>
    {% else %}
        <title>C-Sign</title>
    {% endif %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="A modular covid sign in solution">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    {% if config['FLASK_ENV'] == 'production' %}
        <link rel="stylesheet" type="text/css" href="https://ddjesgdltvd54.cloudfront.net/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="https://ddjesgdltvd54.cloudfront.net/css/Login-Form-Clean.css">
        <link rel="stylesheet" type="text/css" href="https://ddjesgdltvd54.cloudfront.net/css/timeline.css">
    {% else %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/Login-Form-Clean.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/timeline.css') }}">
    {% endif %}
</head>
<body>
    <header class="site-header">
        {% include "nav.html" %}
    </header>
    {% block content %}{% endblock %}
    {% include "footer.html" %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://ddjesgdltvd54.cloudfront.net/js/freelancer.js"></script>
</body>
</html>

src/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="login-clean">
    <h2 class="sr-only">Login Form</h2>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary btn-block") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </div>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
            </small>
</div>
    </form>
</div>
{% endblock content %}

src/templates/nav.html
<nav class="navbar navbar-light navbar-expand-lg fixed-top bg-secondary text-uppercase" id="mainNav">
    <div class="container"><a class="navbar-brand js-scroll-trigger" href="{{ url_for('main.home') }}">C-Sign In</a><button data-toggle="collapse" data-target="#navbarResponsive" class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" aria-controls="navbarResponsive"
            aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item mx-0 mx-lg-1"><a id="contact" class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{{ url_for('main.contact') }}">Contact Us</a></li>
                {% if current_user.is_authenticated %}
                    {% if current_user.admin %}
                        <li class="nav-item mx-0 mx-lg-1"><a id="admin" class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/admin">Admin</a></li>
                    {% endif %}
                    <li class="nav-item mx-0 mx-lg-1"><a id="account" class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{{ url_for('users.account') }}">Account</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{{ url_for('users.logout') }}">Logout</a></li>
                {% else %}
                    <li class="nav-item mx-0 mx-lg-1"><a id="register" class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{{ url_for('users.register') }}">Register</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a id="login" class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{{ url_for('users.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

src/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="login-clean">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

src/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="login-clean">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

src/templates/s_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>C-Sign - {{ title }}</title>
    {% else %}
        <title>C-Sign</title>
    {% endif %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">C-Sign</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Settings</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
          {% block content %}{% endblock %}
        </div>
        {% block todo %}{% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

src/templates/success.html
{% extends "layout.html" %}
{% block content %}
<section class="portfolio" style="margin-top: 50px;">
    <div class="container">
        {% if type %}
                {% if type == 'email' %}
                    <h1>Email Sent!</h1>
                {% endif %}
            {% else %}
                <h1>Great Success!</h1>
            {% endif %}

        <div class="container">
            <img src="https://media1.giphy.com/media/a0h7sAqON67nO/giphy.gif">
            {% if type %}
                {% if type == 'email' %}
                    <p style="margin-top: 25px;">We will get back to you shortly</p>
                {% endif %}
            {% else %}
                <p style="margin-top: 25px;">Have a good time!</p>
            {% endif %}

        </div>
    </div>
</section>
{% endblock content %}